title: hosochinの技術ブログ
description: ""
url: https://hosochin.github.io
baseurl: /tech-blog
permalink: /:title/

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  toc_levels: 1..2
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CLAUDE.md
  - WORK_LOG.md